---
abstract: 'Query a YUM repository for package information '
author:
  - 'Chris Weyl <cweyl@alumni.drew.edu>'
build_requires:
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: lgpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: YUM-RepoQuery
no_index:
  directory:
    - inc
    - t
requires:
  Moose: 0
  MooseX::AttributeHelpers: 0
version: 0.0.2
